#!/usr/bin/env bash
# upload_runs.sh — bundle a user's .run files into a PR for the community dataset
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

RUNS_DIR="data/community_runs"
CONFIG_FILE="data/config.json"

# ── 1. Resolve the user's UUID from config.json ────────────────────────────────
UUID=""
if [ -f "$CONFIG_FILE" ]; then
  UUID="$(python3 -c "import json; d=json.load(open('$CONFIG_FILE')); print(d.get('watcherUserUuid',''))" 2>/dev/null || true)"
fi

if [ -z "$UUID" ]; then
  # Fallback: take the first folder if config has no UUID yet
  for d in "$RUNS_DIR"/*/; do
    [ -d "$d" ] && UUID="$(basename "$d")" && break
  done
fi

if [ -z "$UUID" ]; then
  echo "Could not determine your user UUID."
  echo "Open the app at least once so the watcher can record your UUID."
  exit 1
fi

UUID_DIR="$RUNS_DIR/$UUID"

# Create the folder if it doesn't exist yet
[ -d "$UUID_DIR" ] || mkdir -p "$UUID_DIR"

RUN_COUNT="$(find "$UUID_DIR" -name '*.run' | wc -l | tr -d ' ')"

if [ "$RUN_COUNT" -eq 0 ]; then
  echo "No .run files yet — play a run and the watcher will mirror it here automatically."
  echo "Re-run 'make upload' after your next completed run."
  exit 0
fi

echo "Found $RUN_COUNT run(s) for user $UUID"

# ── 2. Determine base branch ───────────────────────────────────────────────────
BASE_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
if [ "$BASE_BRANCH" = "HEAD" ]; then
  BASE_BRANCH="main"
fi

# ── 3. Create a fresh branch ───────────────────────────────────────────────────
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
BRANCH="runs/${UUID:0:8}-${TIMESTAMP}"

git fetch origin "$BASE_BRANCH" --quiet
git checkout -b "$BRANCH" "origin/$BASE_BRANCH"
echo "Created branch: $BRANCH"

# ── 4. Stage only this user's run files ───────────────────────────────────────
git add "$UUID_DIR"

STAGED="$(git diff --cached --name-only | wc -l | tr -d ' ')"
if [ "$STAGED" -eq 0 ]; then
  echo "No new run files to commit (all already tracked)."
  exit 0
fi

echo "Staging $STAGED file(s)..."
git commit -m "runs: add $RUN_COUNT run(s) from $UUID

User UUID : $UUID
Run files : $RUN_COUNT
Timestamp : $TIMESTAMP"

# ── 5. Push ────────────────────────────────────────────────────────────────────
git push origin "$BRANCH"
echo "Pushed $BRANCH to origin"

# ── 6. Open a PR via the GitHub CLI ───────────────────────────────────────────
if command -v gh &>/dev/null; then
  PR_URL="$(gh pr create \
    --base "$BASE_BRANCH" \
    --head "$BRANCH" \
    --title "Community runs: $UUID ($RUN_COUNT runs)" \
    --body "$(cat <<BODY
## Community run upload

| Field | Value |
|---|---|
| User UUID | \`$UUID\` |
| Run files | $RUN_COUNT |
| Branch | \`$BRANCH\` |

Auto-generated by \`make upload\`.
BODY
)")"
  echo "PR created: $PR_URL"
else
  echo "WARNING: 'gh' CLI not found — skipping PR creation."
  echo "         Open a PR manually from branch: $BRANCH"
  echo "         Install gh: https://cli.github.com"
fi

echo ""
echo "Done! Your runs are on their way to the community dataset."
