# upload_runs.ps1 - bundle a user's .run files into a PR for the community dataset
# Run with: powershell -ExecutionPolicy Bypass -File scripts\upload_runs.ps1
$ErrorActionPreference = "Stop"

$RepoRoot = Split-Path -Parent $PSScriptRoot
Set-Location $RepoRoot

$RunsDir    = "data\community_runs"
$ConfigFile = "data\config.json"

# -- 1. Resolve the user's UUID from config.json --------------------------------
$Uuid = $null
if (Test-Path $ConfigFile) {
    try {
        $cfg  = Get-Content $ConfigFile -Raw | ConvertFrom-Json
        $Uuid = $cfg.watcherUserUuid
    } catch { }
}

if (-not $Uuid) {
    # Fallback: take the first folder if config has no UUID yet
    if (Test-Path $RunsDir) {
        $first = Get-ChildItem -Path $RunsDir -Directory | Select-Object -First 1
        if ($first) { $Uuid = $first.Name }
    }
}

if (-not $Uuid) {
    Write-Host "ERROR: Could not determine your user UUID." -ForegroundColor Red
    Write-Host "       Open the app at least once and play a run so the watcher can record it."
    exit 1
}

$UuidDir = Join-Path $RunsDir $Uuid
if (-not (Test-Path $UuidDir)) {
    Write-Host "ERROR: No run folder found at $UuidDir." -ForegroundColor Red
    Write-Host "       Play at least one complete run so the watcher can mirror it."
    exit 1
}

$RunFiles = Get-ChildItem -Path $UuidDir -Filter "*.run" -Recurse
$RunCount = $RunFiles.Count

if ($RunCount -eq 0) {
    Write-Host "ERROR: No .run files found in $UuidDir." -ForegroundColor Red
    Write-Host "       Play a complete run first, then try again."
    exit 1
}

Write-Host "OK: Found $RunCount run(s) for user $Uuid" -ForegroundColor Green

# -- 2. Determine base branch --------------------------------------------------
$BaseBranch = (git rev-parse --abbrev-ref HEAD).Trim()
if ($BaseBranch -eq "HEAD") { $BaseBranch = "main" }

# Stash any unrelated local changes
$Stashed = $false
git diff --quiet 2>$null
$DiffIdx = $LASTEXITCODE
git diff --cached --quiet 2>$null
$CachIdx = $LASTEXITCODE
if ($DiffIdx -ne 0 -or $CachIdx -ne 0) {
    Write-Host "Stashing uncommitted changes..." -ForegroundColor Yellow
    git stash push -m "upload_runs: auto-stash" --include-untracked
    $Stashed = $true
}

# -- 3. Create a fresh branch --------------------------------------------------
$Timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
$UuidShort = $Uuid.Substring(0, [Math]::Min(8, $Uuid.Length))
$Branch    = "runs/$UuidShort-$Timestamp"

git fetch origin $BaseBranch --quiet
git checkout -b $Branch "origin/$BaseBranch"
Write-Host "Created branch: $Branch" -ForegroundColor Cyan

# -- 4. Stage only this user's run files ---------------------------------------
$RelRunsPath = "data/community_runs/$Uuid"
git add $RelRunsPath

$Staged = (git diff --cached --name-only | Measure-Object -Line).Lines
if ($Staged -eq 0) {
    Write-Host "No new run files to commit (all already tracked)." -ForegroundColor Yellow
    git checkout $BaseBranch
    git branch -D $Branch
    if ($Stashed) { git stash pop }
    exit 0
}

Write-Host "Staging $Staged file(s)..." -ForegroundColor Cyan

$CommitMsg = "runs: add $RunCount run(s) from $Uuid`n`nUser UUID : $Uuid`nRun files : $RunCount`nTimestamp : $Timestamp"
git commit -m $CommitMsg

# -- 5. Push -------------------------------------------------------------------
git push origin $Branch
Write-Host "Pushed $Branch to origin" -ForegroundColor Cyan

# -- 6. Open a PR via the GitHub CLI -------------------------------------------
$GhPath = Get-Command gh -ErrorAction SilentlyContinue
if ($GhPath) {
    $PrTitle = "Community runs: $Uuid ($RunCount runs)"
    $PrBody  = "## Community run upload`n`n| Field | Value |`n|---|---|`n| User UUID | ``$Uuid`` |`n| Run files | $RunCount |`n| Branch | ``$Branch`` |`n`nAuto-generated by ``make upload``."

    $PrUrl = gh pr create --base $BaseBranch --head $Branch --title $PrTitle --body $PrBody
    Write-Host "PR created: $PrUrl" -ForegroundColor Green
} else {
    Write-Host "WARNING: 'gh' CLI not found - skipping PR creation." -ForegroundColor Yellow
    Write-Host "         Open a PR manually from branch: $Branch"
    Write-Host "         Install gh: https://cli.github.com"
}

# -- 7. Restore stash ----------------------------------------------------------
if ($Stashed) {
    git stash pop
    Write-Host "Restored stashed changes" -ForegroundColor Green
}

Write-Host ""
Write-Host "Done! Your runs are on their way to the community dataset." -ForegroundColor Green
