#!/usr/bin/env bash
# upload_runs.sh — bundle a user's .run files into a PR for the community dataset
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

RUNS_DIR="data/community_runs"

# ── 1. Discover the user's UUID folder ────────────────────────────────────────
# Each contributor has exactly one UUID sub-directory under community_runs/.
UUID_DIR=""
for d in "$RUNS_DIR"/*/; do
  [ -d "$d" ] && UUID_DIR="$d" && break
done

if [ -z "$UUID_DIR" ]; then
  echo "❌  No run folder found under $RUNS_DIR."
  echo "    Start the app and play at least one run so the watcher can record it."
  exit 1
fi

UUID="$(basename "$UUID_DIR")"
RUN_COUNT="$(find "$UUID_DIR" -name '*.run' | wc -l | tr -d ' ')"

if [ "$RUN_COUNT" -eq 0 ]; then
  echo "❌  No .run files found in $UUID_DIR."
  echo "    Play a complete run first, then try again."
  exit 1
fi

echo "✅  Found $RUN_COUNT run(s) for user $UUID"

# ── 2. Make sure we're on a clean base ────────────────────────────────────────
BASE_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
if [ "$BASE_BRANCH" = "HEAD" ]; then
  BASE_BRANCH="main"
fi

# Stash any unrelated local changes so they don't sneak into the PR
STASHED=false
if ! git diff --quiet || ! git diff --cached --quiet; then
  echo "⚠️   Stashing uncommitted changes…"
  git stash push -m "upload_runs: auto-stash" --include-untracked
  STASHED=true
fi

# ── 3. Create a fresh branch ───────────────────────────────────────────────────
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
BRANCH="runs/${UUID:0:8}-${TIMESTAMP}"

git fetch origin "$BASE_BRANCH" --quiet
git checkout -b "$BRANCH" "origin/$BASE_BRANCH"
echo "🌿  Created branch: $BRANCH"

# ── 4. Stage only this user's run files ───────────────────────────────────────
git add "$UUID_DIR"

STAGED="$(git diff --cached --name-only | wc -l | tr -d ' ')"
if [ "$STAGED" -eq 0 ]; then
  echo "ℹ️   No new run files to commit (all already tracked)."
  git checkout "$BASE_BRANCH"
  git branch -D "$BRANCH"
  [ "$STASHED" = true ] && git stash pop
  exit 0
fi

echo "📦  Staging $STAGED file(s)…"
git commit -m "runs: add $RUN_COUNT run(s) from $UUID

User UUID : $UUID
Run files : $RUN_COUNT
Timestamp : $TIMESTAMP"

# ── 5. Push ────────────────────────────────────────────────────────────────────
git push origin "$BRANCH"
echo "⬆️   Pushed $BRANCH to origin"

# ── 6. Open a PR via the GitHub CLI ───────────────────────────────────────────
if command -v gh &>/dev/null; then
  PR_URL="$(gh pr create \
    --base "$BASE_BRANCH" \
    --head "$BRANCH" \
    --title "Community runs: $UUID ($RUN_COUNT runs)" \
    --body "$(cat <<BODY
## Community run upload

| Field | Value |
|---|---|
| User UUID | \`$UUID\` |
| Run files | $RUN_COUNT |
| Branch | \`$BRANCH\` |

Auto-generated by \`make upload\`.
BODY
)")"
  echo "🎉  PR created: $PR_URL"
else
  echo "⚠️   \`gh\` CLI not found — skipping PR creation."
  echo "    Open a PR manually from branch: $BRANCH"
  echo "    Install gh: https://cli.github.com"
fi

# ── 7. Restore stash if we stashed earlier ────────────────────────────────────
git checkout "$BASE_BRANCH"
[ "$STASHED" = true ] && git stash pop && echo "✅  Restored stashed changes"

echo ""
echo "Done! Your runs are on their way to the community dataset. 🗡️"
